acq_func: UCB
context_dim: 4
experiment_name: example_1d_forrester
input_dim: 3
log_dir: C:\Users\youse\PycharmProjects\bayesopt4ros\src\bayesopt4ros
lower_bound:
- 0.5
- 0.95
- 0.5
max_iter: 10000
maximize: true
n_init: 3
upper_bound:
- 2.0
- 1.1
- 1.5
