acq_func: UCB
context_dim: 4
experiment_name: example_1d_forrester
input_dim: 3
log_dir: C:\Users\youse\PycharmProjects\bayesopt4ros\root
lower_bound:
- 0.75
- 0.99
- 1.0
max_iter: 10000
maximize: true
n_init: 3
upper_bound:
- 1.5
- 1.01
- 1.1
