acq_func: UCB
context_dim: 1
experiment_name: example_1d_forrester
input_dim: 1
log_dir: C:\Users\youse\PycharmProjects\bayesopt4ros\root
lower_bound:
- 0.0
max_iter: 10
maximize: true
n_init: 3
upper_bound:
- 2.0
